/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic.java.docker.jdbc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JdbcDockerAppTest {
    @Test void appHasAGreeting() {
        JdbcDockerApp classUnderTest = new JdbcDockerApp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
