version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my-database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  jdbc-app:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: jdbc-docker-app-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"

volumes:
  mysql_data:
