/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic.java.docker;

public class Application {
    public String getGreeting() {
        return "Hello World! This is a Basic Java App containerised with Docker.";
    }

    public static void main(String[] args) {
        System.out.println(new Application().getGreeting());
    }
}
