/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basic.java.docker.jdbc;

public class JdbcDockerApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new JdbcDockerApp().getGreeting());
    }
}
